const USE_CASE_TYPES = {
  DebugUseCase: Symbol.for("DebugUseCase"),
  GetHomeAnimalsUseCase: Symbol.for("GetHomeAnimalsUseCase"),
  GetAnimalsUseCase: Symbol.for("GetAnimalsUseCase"),
  GetAnimalByIdUseCase: Symbol.for("GetAnimalByIdUseCase"),
  GetAdoptCatalogUseCase: Symbol.for("GetAdoptCatalogUseCase"),
  GetAdoptDetailUseCase: Symbol.for("GetAdoptDetailUseCase"),
  GetAdminAdoptionRequestsUseCase: Symbol.for("GetAdminAdoptionRequestsUseCase"),
  GetAdoptionRequestDetailUseCase: Symbol.for("GetAdoptionRequestDetailUseCase"),
  UpdateAdoptionRequestStatusUseCase: Symbol.for("UpdateAdoptionRequestStatusUseCase"),
  GetDashboardDataUseCase: Symbol.for("GetDashboardDataUseCase"),
  CreateAnimalUseCase: Symbol.for("CreateAnimalUseCase"),
  DeleteAnimalUseCase: Symbol.for("DeleteAnimalUseCase"),
  UpdateAnimalUseCase: Symbol.for("UpdateAnimalUseCase"),
  RegisterFoundationUseCase: Symbol.for("RegisterFoundationUseCase"),
  LoginUseCase: Symbol.for("LoginUseCase"),
  GetSessionUseCase: Symbol.for("GetSessionUseCase"),
  GetFoundationProfileUseCase: Symbol.for("GetFoundationProfileUseCase"),
  UpdateFoundationProfileUseCase: Symbol.for("UpdateFoundationProfileUseCase"),
  GetShopCatalogUseCase: Symbol.for("GetShopCatalogUseCase"),
  GetProductsUseCase: Symbol.for("GetProductsUseCase"),
  CreateProductUseCase: Symbol.for("CreateProductUseCase"),
  GetProductByIdUseCase: Symbol.for("GetProductByIdUseCase"),
  UpdateProductPublishStatusUseCase: Symbol.for("UpdateProductPublishStatusUseCase"),
  DeleteProductUseCase: Symbol.for("DeleteProductUseCase"),
  UpdateProductUseCase: Symbol.for("UpdateProductUseCase"),
};

export { USE_CASE_TYPES };
